# Generated by Django 3.1.7 on 2021-07-09 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='Family',
            field=models.CharField(max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='Name',
            field=models.CharField(max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربری'),
        ),
    ]
