# Generated by Django 3.1.7 on 2021-06-19 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='concertModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='فروش بلیط کنسرت')),
                ('SingerName', models.CharField(max_length=100, verbose_name='نام خواننده')),
                ('lenght', models.IntegerField(verbose_name='مدت زمان')),
                ('test', models.CharField(max_length=10, null=True, verbose_name='تست')),
                ('Poster', models.ImageField(null=True, upload_to='concertImages/', verbose_name='پوستر')),
            ],
            options={
                'verbose_name': 'کنسرت',
                'verbose_name_plural': 'کنسرت',
            },
        ),
        migrations.CreateModel(
            name='locationModel',
            fields=[
                ('IdNumber', models.IntegerField(primary_key=True, serialize=False, verbose_name='آیدی')),
                ('Name', models.CharField(max_length=100, verbose_name='نام')),
                ('Address', models.CharField(default='تهران-برج میلاد', max_length=500, verbose_name='آدرس ')),
                ('Phone', models.CharField(max_length=11, null=True, verbose_name='تلفن')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
            ],
            options={
                'verbose_name': ' مکان برگذاری  ',
                'verbose_name_plural': 'مکان برگذاری',
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام')),
                ('Family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('ProfileImage', models.ImageField(upload_to='ProfileImages/', verbose_name='  تصویر پروفایل')),
                ('Gender', models.IntegerField(choices=[('Man', 'مرد'), ('Woman', 'زن')], verbose_name=' جنسیت ')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر',
            },
        ),
        migrations.CreateModel(
            name='timeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDateTime', models.DateTimeField(verbose_name='تاریخ برگذاری')),
                ('seats', models.IntegerField(verbose_name='تعداد صندلی')),
                ('Status', models.IntegerField(choices=[('start', 'فروش بلیط شروع شده است'), ('End', 'فروش بلیط تمام شده است'), ('Cancle', 'این سانس کنسل شده است'), ('Sales', 'در حال فروش بلیط')], verbose_name='وضعیت')),
                ('concertModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.concertmodel', verbose_name=' کنسرت')),
                ('locationModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.locationmodel', verbose_name=' مکان برگذاری')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس',
            },
        ),
        migrations.CreateModel(
            name='ticketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketImage', models.ImageField(upload_to='TicketImages/', verbose_name=' تصویر بلیط ')),
                ('Name', models.CharField(max_length=100, verbose_name='نام')),
                ('Price', models.IntegerField(verbose_name='قیمت')),
                ('ProfileModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.profilemodel', verbose_name='پروفایل')),
                ('timeModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.timemodel', verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط',
            },
        ),
    ]
