# Generated by Django 3.1.7 on 2021-06-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertmodel',
            name='test',
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name=' نام کنسرت'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Status',
            field=models.IntegerField(choices=[(1, 'فروش بلیط شروع شده است'), (2, 'فروش بلیط تمام شده است'), (3, 'این سانس کنسل شده است'), (4, 'در حال فروش بلیط')], verbose_name='وضعیت'),
        ),
    ]
