# Generated by Django 3.1.7 on 2021-07-09 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('ticketSales', '0002_auto_20210628_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='ProfileModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profilemodel', verbose_name='پروفایل'),
        ),
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
